services:
  tg-api:
    restart: unless-stopped
    image: ghcr.io/aramann/tg-api:latest
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
    volumes:
      - tg-api-data:/app/api_data
    networks:
      tg_api:
        aliases:
          - tg-api

volumes:
  tg-api-data:
    external: true

networks:
  tg_api:
    external: true
